jup_sh:
  user_home: /tmp
  user_name: jup_git
  environment: production
repos:
  root_dir: /tmp/gits
  repo_user: jup_git
git:
  repo_path: git
  host: localhost
  shell: /opt/local/bin/git-shell
shell:
  path: /var/opt/jupiler/jupiler-sh.rb
logs:
  email: email.log
  scm: scm.log
  jup_sh: jup_sh.log
  